"""add data provenance models

Revision ID: a7dd7ddf30b9
Revises: 78cc3016c6ae
Create Date: 2026-09-14 19:54:16.166185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7dd7ddf30b9'
down_revision = '78cc3016c6ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_sources_slug'), ['slug'], unique=True)

    op.create_table('product_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'source_id', 'source_url', name='uq_product_source_link')
    )
    with op.batch_alter_table('product_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_sources_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_sources_source_id'), ['source_id'], unique=False)

    op.create_table('specification_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specification_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['specification_id'], ['specifications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('specification_id', 'source_id', 'source_url', name='uq_specification_source_link')
    )
    with op.batch_alter_table('specification_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_specification_sources_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_specification_sources_specification_id'), ['specification_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specification_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_specification_sources_specification_id'))
        batch_op.drop_index(batch_op.f('ix_specification_sources_source_id'))

    op.drop_table('specification_sources')
    with op.batch_alter_table('product_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_sources_source_id'))
        batch_op.drop_index(batch_op.f('ix_product_sources_product_id'))

    op.drop_table('product_sources')
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_sources_slug'))

    op.drop_table('data_sources')
    # ### end Alembic commands ###
